import { FoodInsert, FoodItemInsert } from "@/types/food";
import { IngredientItemInsert } from "@/types/recipe";
import { ServingSizeType } from "@/types/servingSize";
import { WeightHistoryRecord } from "@/types/weight";

export const TestFood1: FoodInsert = {
	name: "TEST FOOD WITH A REALLY LONG NAME FOR NO REASON",
	nickname: "TESTFOOD1",
	protein: 30,
	fat: 15,
	carbs: 55,
	fiber: 8,
	barcode: "1",
	serving_100g: 1,
	volume_100ml: 1,
	micro_nutriants: {
		testmacro1: 12,
		testmacro2: 13,
	},
};

export const TestFood2: FoodInsert = {
	name: "TESTFOOD2",
	nickname: "TESTFOOD2",
	protein: 5,
	fat: 2,
	carbs: 10,
	fiber: 1,
	barcode: "2",
	serving_100g: 50,
	volume_100ml: 30,
	micro_nutriants: {
		testmacro1: 20,
		testmacro2: 21,
	},
};

export const TestFood3: FoodInsert = {
	name: "TESTFOOD3",
	nickname: "TESTFOOD3",
	protein: 12,
	fat: 4,
	carbs: 18,
	fiber: 2,
	barcode: "3",
	serving_100g: 100,
	volume_100ml: 80,
	micro_nutriants: {
		testmacro1: 30,
		testmacro2: 31,
	},
};

export const TestFood4: FoodInsert = {
	name: "TESTFOOD4",
	nickname: "TESTFOOD4",
	protein: 20,
	fat: 10,
	carbs: 25,
	fiber: 3,
	barcode: "4",
	serving_100g: 150,
	volume_100ml: 120,
	micro_nutriants: {
		testmacro1: 40,
		testmacro2: 41,
	},
};
export const FoodDefault: FoodInsert = {
	name: "",
	protein: 0,
	fat: 0,
	carbs: 0,
	fiber: 0,
	barcode: "0",
	serving_100g: 0,
	volume_100ml: 0,
};

export const TestFoodItem1: Omit<FoodItemInsert, "food_id"> = {
	serving_type: "g",
	servings: 1,
	serving_mult: 1,
};
export const TestFoodItem2: Omit<FoodItemInsert, "food_id"> = {
	serving_type: "g",
	servings: 1.5,
	serving_mult: 1,
};
export const TestFoodItem3: Omit<FoodItemInsert, "food_id"> = {
	serving_type: "g",
	servings: 2,
	serving_mult: 1,
};
export const FoodItemDefault: Omit<FoodItemInsert, "food_id"> = {
	serving_type: "Serving",
	servings: 1,
	serving_mult: 1,
};
export const TestIngredientItem1: Omit<IngredientItemInsert, "recipe_id"> = {
	serving_type: "Grams",
	ingredient_id: 1,
	servings: 40,
	serving_mult: 1,
};
export const TestIngredientItem2: Omit<IngredientItemInsert, "recipe_id"> = {
	serving_type: "Grams",
	ingredient_id: 2,
	servings: 1,
	serving_mult: 1,
};
export const TestIngredientItem3: Omit<IngredientItemInsert, "recipe_id"> = {
	serving_type: "Grams",
	ingredient_id: 3,
	servings: 1,
	serving_mult: 1,
};

export const DefaultServings: Omit<ServingSizeType, "food_id">[] = [
	{ serving_type: "Gram", serving_mult: 0.01 },
	{ serving_type: "Serving", serving_mult: 1 },
	{ serving_type: "lb", serving_mult: 2 },
	{ serving_type: "Cup", serving_mult: 3 },
];

export const TESTFOODITEMDATA: FoodItemInsert[] = [
	{
		food_id: 9,
		serving_type: "Serving",
		servings: 125,
		serving_mult: 1,
		timestamp: new Date("2026-03-31"),
	},
	{
		food_id: 10,
		serving_type: "Serving",
		servings: 245,
		serving_mult: 1,
		timestamp: new Date("2026-03-31"),
	},
	{
		food_id: 11,
		serving_type: "Serving",
		servings: 65,
		serving_mult: 1,
		timestamp: new Date("2026-03-31"),
	},
];

export const weightHistoryTestData: WeightHistoryRecord[] = [
	{
		timestamp: new Date("2026-05-17T08:00:00Z"),
		weight: 165.8,
		count: 1,
		minWeight: 165.8,
		maxWeight: 165.8,
	},
	{
		timestamp: new Date("2026-05-18T08:15:00Z"),
		weight: 166.4,
		count: 1,
		minWeight: 166.4,
		maxWeight: 166.4,
	},
	{
		timestamp: new Date("2026-05-19T07:45:00Z"),
		weight: 164.9,
		count: 2,
		minWeight: 164.4,
		maxWeight: 165.3,
	},
	{
		timestamp: new Date("2026-05-20T08:30:00Z"),
		weight: 165.5,
		count: 1,
		minWeight: 165.5,
		maxWeight: 165.5,
	},
	{
		timestamp: new Date("2026-05-21T07:30:00Z"),
		weight: 165.1,
		count: 3,
		minWeight: 164.2,
		maxWeight: 166.0,
	},
	{
		timestamp: new Date("2026-05-22T08:00:00Z"),
		weight: 165.9,
		count: 2,
		minWeight: 165.3,
		maxWeight: 166.6,
	},
	{
		timestamp: new Date("2026-05-23T09:00:00Z"),
		weight: 164.6,
		count: 1,
		minWeight: 164.6,
		maxWeight: 164.6,
	},
	{
		timestamp: new Date("2026-05-24T08:15:00Z"),
		weight: 166.2,
		count: 2,
		minWeight: 165.6,
		maxWeight: 166.8,
	},
	{
		timestamp: new Date("2026-05-25T07:50:00Z"),
		weight: 165.2,
		count: 1,
		minWeight: 165.2,
		maxWeight: 165.2,
	},
	{
		timestamp: new Date("2026-05-26T08:45:00Z"),
		weight: 165.7,
		count: 2,
		minWeight: 165.1,
		maxWeight: 166.4,
	},
];

export const foodFullDataList = [
	// May 20, 2026
	{
		food: {
			name: "Chicken Breast",
			nickname: "Chicken",
			protein: 31,
			fat: 3.6,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 165,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 0,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-20T07:30:00Z"),
		},
	},
	{
		food: {
			name: "Brown Rice",
			nickname: "Rice",
			protein: 2.6,
			fat: 0.9,
			carbs: 23,
			fiber: 1.8,
			barcode: null,
			serving_100g: 150,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 1,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-20T07:30:00Z"),
		},
	},
	{
		food: {
			name: "Banana",
			nickname: null,
			protein: 1.1,
			fat: 0.3,
			carbs: 23,
			fiber: 2.6,
			barcode: null,
			serving_100g: 118,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 2,
			servings: 1,
			serving_mult: 118,
			serving_type: "g",
			timestamp: new Date("2026-05-20T10:00:00Z"),
		},
	},
	{
		food: {
			name: "Whole Wheat Bread",
			nickname: "Bread",
			protein: 4,
			fat: 1.5,
			carbs: 41,
			fiber: 7,
			barcode: null,
			serving_100g: 28,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 3,
			servings: 2,
			serving_mult: 28,
			serving_type: "slice",
			timestamp: new Date("2026-05-20T12:30:00Z"),
		},
	},
	{
		food: {
			name: "Peanut Butter",
			nickname: "PB",
			protein: 7,
			fat: 16,
			carbs: 7,
			fiber: 1.5,
			barcode: null,
			serving_100g: 16,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 4,
			servings: 2,
			serving_mult: 16,
			serving_type: "tbsp",
			timestamp: new Date("2026-05-20T12:30:00Z"),
		},
	},
	{
		food: {
			name: "Salmon",
			nickname: null,
			protein: 25,
			fat: 13,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 178,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 8,
			servings: 1,
			serving_mult: 178,
			serving_type: "g",
			timestamp: new Date("2026-05-20T18:00:00Z"),
		},
	},
	{
		food: {
			name: "Broccoli",
			nickname: null,
			protein: 2.8,
			fat: 0.4,
			carbs: 7,
			fiber: 2.4,
			barcode: null,
			serving_100g: 91,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 7,
			servings: 2,
			serving_mult: 91,
			serving_type: "cup",
			timestamp: new Date("2026-05-20T18:00:00Z"),
		},
	},

	// May 21, 2026
	{
		food: {
			name: "Oats",
			nickname: null,
			protein: 10,
			fat: 5,
			carbs: 54,
			fiber: 8,
			barcode: null,
			serving_100g: 40,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 6,
			servings: 1,
			serving_mult: 40,
			serving_type: "cup",
			timestamp: new Date("2026-05-21T07:00:00Z"),
		},
	},
	{
		food: {
			name: "Greek Yogurt",
			nickname: "Yogurt",
			protein: 10,
			fat: 0.4,
			carbs: 3.6,
			fiber: 0,
			barcode: null,
			serving_100g: 100,
			volume_100ml: 100,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 9,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-21T07:00:00Z"),
		},
	},
	{
		food: {
			name: "Banana",
			nickname: null,
			protein: 1.1,
			fat: 0.3,
			carbs: 23,
			fiber: 2.6,
			barcode: null,
			serving_100g: 118,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 2,
			servings: 1,
			serving_mult: 118,
			serving_type: "g",
			timestamp: new Date("2026-05-21T10:00:00Z"),
		},
	},
	{
		food: {
			name: "Chicken Breast",
			nickname: "Chicken",
			protein: 31,
			fat: 3.6,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 165,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 0,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-21T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Brown Rice",
			nickname: "Rice",
			protein: 2.6,
			fat: 0.9,
			carbs: 23,
			fiber: 1.8,
			barcode: null,
			serving_100g: 150,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 1,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-21T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Eggs",
			nickname: null,
			protein: 6,
			fat: 5,
			carbs: 0.6,
			fiber: 0,
			barcode: null,
			serving_100g: 50,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 5,
			servings: 2,
			serving_mult: 50,
			serving_type: "egg",
			timestamp: new Date("2026-05-21T19:00:00Z"),
		},
	},
	{
		food: {
			name: "Whole Wheat Bread",
			nickname: "Bread",
			protein: 4,
			fat: 1.5,
			carbs: 41,
			fiber: 7,
			barcode: null,
			serving_100g: 28,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 3,
			servings: 2,
			serving_mult: 28,
			serving_type: "slice",
			timestamp: new Date("2026-05-21T19:00:00Z"),
		},
	},

	// May 22, 2026
	{
		food: {
			name: "Eggs",
			nickname: null,
			protein: 6,
			fat: 5,
			carbs: 0.6,
			fiber: 0,
			barcode: null,
			serving_100g: 50,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 5,
			servings: 3,
			serving_mult: 50,
			serving_type: "egg",
			timestamp: new Date("2026-05-22T07:30:00Z"),
		},
	},
	{
		food: {
			name: "Whole Wheat Bread",
			nickname: "Bread",
			protein: 4,
			fat: 1.5,
			carbs: 41,
			fiber: 7,
			barcode: null,
			serving_100g: 28,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 3,
			servings: 2,
			serving_mult: 28,
			serving_type: "slice",
			timestamp: new Date("2026-05-22T07:30:00Z"),
		},
	},
	{
		food: {
			name: "Greek Yogurt",
			nickname: "Yogurt",
			protein: 10,
			fat: 0.4,
			carbs: 3.6,
			fiber: 0,
			barcode: null,
			serving_100g: 100,
			volume_100ml: 100,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 9,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-22T10:30:00Z"),
		},
	},
	{
		food: {
			name: "Chicken Breast",
			nickname: "Chicken",
			protein: 31,
			fat: 3.6,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 165,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 0,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-22T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Broccoli",
			nickname: null,
			protein: 2.8,
			fat: 0.4,
			carbs: 7,
			fiber: 2.4,
			barcode: null,
			serving_100g: 91,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 7,
			servings: 2,
			serving_mult: 91,
			serving_type: "cup",
			timestamp: new Date("2026-05-22T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Brown Rice",
			nickname: "Rice",
			protein: 2.6,
			fat: 0.9,
			carbs: 23,
			fiber: 1.8,
			barcode: null,
			serving_100g: 150,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 1,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-22T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Salmon",
			nickname: null,
			protein: 25,
			fat: 13,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 178,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 8,
			servings: 1,
			serving_mult: 178,
			serving_type: "g",
			timestamp: new Date("2026-05-22T18:30:00Z"),
		},
	},

	// May 23, 2026
	{
		food: {
			name: "Oats",
			nickname: null,
			protein: 10,
			fat: 5,
			carbs: 54,
			fiber: 8,
			barcode: null,
			serving_100g: 40,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 6,
			servings: 1,
			serving_mult: 40,
			serving_type: "cup",
			timestamp: new Date("2026-05-23T07:00:00Z"),
		},
	},
	{
		food: {
			name: "Banana",
			nickname: null,
			protein: 1.1,
			fat: 0.3,
			carbs: 23,
			fiber: 2.6,
			barcode: null,
			serving_100g: 118,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 2,
			servings: 1,
			serving_mult: 118,
			serving_type: "g",
			timestamp: new Date("2026-05-23T07:00:00Z"),
		},
	},
	{
		food: {
			name: "Peanut Butter",
			nickname: "PB",
			protein: 7,
			fat: 16,
			carbs: 7,
			fiber: 1.5,
			barcode: null,
			serving_100g: 16,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 4,
			servings: 2,
			serving_mult: 16,
			serving_type: "tbsp",
			timestamp: new Date("2026-05-23T10:00:00Z"),
		},
	},
	{
		food: {
			name: "Chicken Breast",
			nickname: "Chicken",
			protein: 31,
			fat: 3.6,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 165,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 0,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-23T12:30:00Z"),
		},
	},
	{
		food: {
			name: "Brown Rice",
			nickname: "Rice",
			protein: 2.6,
			fat: 0.9,
			carbs: 23,
			fiber: 1.8,
			barcode: null,
			serving_100g: 150,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 1,
			servings: 1.5,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-23T12:30:00Z"),
		},
	},
	{
		food: {
			name: "Eggs",
			nickname: null,
			protein: 6,
			fat: 5,
			carbs: 0.6,
			fiber: 0,
			barcode: null,
			serving_100g: 50,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 5,
			servings: 2,
			serving_mult: 50,
			serving_type: "egg",
			timestamp: new Date("2026-05-23T19:00:00Z"),
		},
	},
	{
		food: {
			name: "Broccoli",
			nickname: null,
			protein: 2.8,
			fat: 0.4,
			carbs: 7,
			fiber: 2.4,
			barcode: null,
			serving_100g: 91,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 7,
			servings: 1,
			serving_mult: 91,
			serving_type: "cup",
			timestamp: new Date("2026-05-23T19:00:00Z"),
		},
	},

	// May 24, 2026
	{
		food: {
			name: "Greek Yogurt",
			nickname: "Yogurt",
			protein: 10,
			fat: 0.4,
			carbs: 3.6,
			fiber: 0,
			barcode: null,
			serving_100g: 100,
			volume_100ml: 100,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 9,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-24T07:30:00Z"),
		},
	},
	{
		food: {
			name: "Oats",
			nickname: null,
			protein: 10,
			fat: 5,
			carbs: 54,
			fiber: 8,
			barcode: null,
			serving_100g: 40,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 6,
			servings: 1,
			serving_mult: 40,
			serving_type: "cup",
			timestamp: new Date("2026-05-24T07:30:00Z"),
		},
	},
	{
		food: {
			name: "Banana",
			nickname: null,
			protein: 1.1,
			fat: 0.3,
			carbs: 23,
			fiber: 2.6,
			barcode: null,
			serving_100g: 118,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 2,
			servings: 1,
			serving_mult: 118,
			serving_type: "g",
			timestamp: new Date("2026-05-24T10:30:00Z"),
		},
	},
	{
		food: {
			name: "Salmon",
			nickname: null,
			protein: 25,
			fat: 13,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 178,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 8,
			servings: 1,
			serving_mult: 178,
			serving_type: "g",
			timestamp: new Date("2026-05-24T13:30:00Z"),
		},
	},
	{
		food: {
			name: "Brown Rice",
			nickname: "Rice",
			protein: 2.6,
			fat: 0.9,
			carbs: 23,
			fiber: 1.8,
			barcode: null,
			serving_100g: 150,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 1,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-24T13:30:00Z"),
		},
	},
	{
		food: {
			name: "Chicken Breast",
			nickname: "Chicken",
			protein: 31,
			fat: 3.6,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 165,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 0,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-24T18:00:00Z"),
		},
	},
	{
		food: {
			name: "Broccoli",
			nickname: null,
			protein: 2.8,
			fat: 0.4,
			carbs: 7,
			fiber: 2.4,
			barcode: null,
			serving_100g: 91,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 7,
			servings: 2,
			serving_mult: 91,
			serving_type: "cup",
			timestamp: new Date("2026-05-24T18:00:00Z"),
		},
	},

	// May 25, 2026
	{
		food: {
			name: "Eggs",
			nickname: null,
			protein: 6,
			fat: 5,
			carbs: 0.6,
			fiber: 0,
			barcode: null,
			serving_100g: 50,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 5,
			servings: 3,
			serving_mult: 50,
			serving_type: "egg",
			timestamp: new Date("2026-05-25T07:00:00Z"),
		},
	},
	{
		food: {
			name: "Whole Wheat Bread",
			nickname: "Bread",
			protein: 4,
			fat: 1.5,
			carbs: 41,
			fiber: 7,
			barcode: null,
			serving_100g: 28,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 3,
			servings: 2,
			serving_mult: 28,
			serving_type: "slice",
			timestamp: new Date("2026-05-25T07:00:00Z"),
		},
	},
	{
		food: {
			name: "Peanut Butter",
			nickname: "PB",
			protein: 7,
			fat: 16,
			carbs: 7,
			fiber: 1.5,
			barcode: null,
			serving_100g: 16,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 4,
			servings: 1,
			serving_mult: 16,
			serving_type: "tbsp",
			timestamp: new Date("2026-05-25T10:00:00Z"),
		},
	},
	{
		food: {
			name: "Chicken Breast",
			nickname: "Chicken",
			protein: 31,
			fat: 3.6,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 165,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 0,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-25T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Brown Rice",
			nickname: "Rice",
			protein: 2.6,
			fat: 0.9,
			carbs: 23,
			fiber: 1.8,
			barcode: null,
			serving_100g: 150,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 1,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-25T13:00:00Z"),
		},
	},
	{
		food: {
			name: "Greek Yogurt",
			nickname: "Yogurt",
			protein: 10,
			fat: 0.4,
			carbs: 3.6,
			fiber: 0,
			barcode: null,
			serving_100g: 100,
			volume_100ml: 100,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 9,
			servings: 1,
			serving_mult: 150,
			serving_type: "g",
			timestamp: new Date("2026-05-25T15:00:00Z"),
		},
	},
	{
		food: {
			name: "Salmon",
			nickname: null,
			protein: 25,
			fat: 13,
			carbs: 0,
			fiber: 0,
			barcode: null,
			serving_100g: 178,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 8,
			servings: 1,
			serving_mult: 178,
			serving_type: "g",
			timestamp: new Date("2026-05-25T19:00:00Z"),
		},
	},
	{
		food: {
			name: "Broccoli",
			nickname: null,
			protein: 2.8,
			fat: 0.4,
			carbs: 7,
			fiber: 2.4,
			barcode: null,
			serving_100g: 91,
			volume_100ml: 0,
			micro_nutriants: {},
			recipe_id: null,
		},
		foodItem: {
			food_id: 7,
			servings: 1,
			serving_mult: 91,
			serving_type: "cup",
			timestamp: new Date("2026-05-25T19:00:00Z"),
		},
	},
];
